apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: argocd-proj2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: qslrdocker/argocd-proj2:v001
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: argocd-proj2
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
