apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-proj2
  namespace: argocd-proj2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-proj2
  template:
    metadata:
      labels:
        app: argocd-proj2
    spec:
      containers:
        - name: argocd-proj2
          image: qslrdocker/argocd-proj2:v001
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-proj2-service
  namespace: argocd-proj2
spec:
  selector:
    app: argocd-proj2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
