apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-proj2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/robertocamp/argocd-proj2'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-proj2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
